### ISSUE TITLE
Migrate to klog and add customization (like logging in json)

### ISSUE THREAD

**Issue by grzesuav** [metacontroller/metacontroller#38]
https://github.com/AmitKumarDas/metac/issues/134

https://github.com/AmitKumarDas/metac/issues/110

**Comment by grzesuav** [comment]
Actually some of kubernetes dependencies are using `glog`, and because of that we got https://github.com/kubernetes/kubernetes/issues/74560 .

```
/usr/bin/metacontroller flag redefined: log_dir
panic: /usr/bin/metacontroller flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000076180, 0x12cd020, 0x1a96070, 0x1151c08, 0x7, 0x117a516, 0x2f)
        /usr/local/go/src/flag/flag.go:851 +0x4b8
flag.(*FlagSet).StringVar(...)
        /usr/local/go/src/flag/flag.go:754
k8s.io/klog.InitFlags(0x0)
        /go/src/metacontroller.io/vendor/k8s.io/klog/klog.go:411 +0xa2
main.main()
        /go/src/metacontroller.io/main.go:50 +0x96
```

**Comment by grzesuav** [comment]
https://github.com/metacontroller/metacontroller/pull/152

**Comment by grzesuav** [comment]
This is first part, migrating to klog. Actually klog does not support json out of the box. 

There is a way to do it, like recent changes in k8s :
* https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/
it will be good to follow in the same direction.
Their migration guide (to utilize structured logging) is here - https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md - along with some guidelines which seems good to adopt.

Logging in json is no so straightforward - while reading: 
* https://github.com/kubernetes/kubernetes/pull/91608/
* https://github.com/kubernetes/enhancements/issues/1602 
* https://github.com/kubernetes/kubernetes/pull/89683

it seems the way they choose is :
* implement https://github.com/go-logr/logr interface (https://github.com/kubernetes/klog/tree/master/klogr)
* use https://github.com/go-logr/zapr interface to use https://github.com/uber-go/zap

**Comment by grzesuav** [comment]
Actually migration to `json` and `logr` as an logging interface and `zapr` as backend is simple, but would take some time.


The problematic part is showing line number of the log line, given there are several interceptors.

For example, having this piece of code :
```go
	klog.InfoS("Discovery cache flush interval", "discovery_interval", *discoveryInterval)
	klog.InfoS("API server object cache flush interval", "cache_flush_interval", *informerRelist)
	klog.InfoS("Http server address", "port", *debugAddr)

	var config *rest.Config
	var err error
	if *clientConfigPath != "" {
		klog.Infof("Using current context from kubeconfig file: %v", *clientConfigPath)
		config, err = clientcmd.BuildConfigFromFlags("", *clientConfigPath)
	} else {
		klog.Info("No kubeconfig file specified; trying in-cluster auto-config...")
		config, err = rest.InClusterConfig()
	}
```

we get this log :
```json
{"level":"info","ts":1610747890.08661,"caller":"metacontroller.io/main.go:74","msg":"Discovery cache flush interval","discovery_interval":5}
{"level":"info","ts":1610747890.0868678,"caller":"metacontroller.io/main.go:75","msg":"API server object cache flush interval","cache_flush_interval":1800}
{"level":"info","ts":1610747890.086895,"caller":"metacontroller.io/main.go:76","msg":"Http server address","port":":9999"}
{"level":"info","ts":1610747890.0869858,"caller":"v2/klog.go:714","msg":"No kubeconfig file specified; trying in-cluster auto-config...\n"}

```

as you might notice, the discrepancies between `klog.InfoS` (structured logging) and `klog.Info` (unstructured) are :
* wrong line reported - as line is computed from call stack, and both methods have different dept, it is impossible to set correct value for both at the same time
* newlines in unstructured logging



I guess we could :
* first release `json` logging as `beta` - and then slowly migrate (package by package) from `klog`-unstructured to `klog`-structured having more and more logs correct, finally receiving desired state.
* do not expose option to log in in json until above is finished - so make it available when it will be ready

**Comment by grzesuav** [comment]
After migration - use linter to check if old statement's aren't introduced - https://github.com/kubernetes/klog/tree/master/hack/tools/logcheck

**Comment by grzesuav** [comment]
As both changes are merged - closing. For the leftover issue (allow to log in in json format) I will create new issue
