### ISSUE TITLE
Panic in controller Go code

### ISSUE THREAD

**Issue by nycnewman** [metacontroller/metacontroller#644]
Received a panic when trying to apply a CRD. CRD works for one instance but this specific instance causes the metacontroller to die.

What else can I provide to help traige?

```json
{"level":"error","ts":1662454339.0242538,"msg":"Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)\ngoroutine 643 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x1054040?, 0x1f1e7b0})\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/runtime/runtime.go:75 +0x84\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x40004fd180?})\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/runtime/runtime.go:49 +0x84\npanic({0x1054040, 0x1f1e7b0})\n\t/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x20c\nk8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetAPIVersion(...)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/apis/meta/v1/unstructured/unstructured.go:218\nk8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GroupVersionKind(0x0)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/apis/meta/v1/unstructured/unstructured.go:426 +0x44\nmetacontroller/pkg/controller/common/api/v1.RelativeObjectMap.Insert(0x0?, {0x146a9f8, 0x40005864d8}, 0x0)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/common/api/v1/common.go:36 +0x3c\nmetacontroller/pkg/controller/common/api/v1.RelativeObjectMap.InsertAll(...)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/common/api/v1/common.go:48\nmetacontroller/pkg/controller/common/api/v1.MakeRelativeObjectMap({0x146a9f8, 0x40005864d8}, {0x400037ef00, 0x8, 0x4000ac78f8?})\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/common/api/v1/common.go:127 +0x54\nmetacontroller/pkg/controller/composite.(*parentController).syncParentObject(0x40001fcc40, 0x40005864d8)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:533 +0x268\nmetacontroller/pkg/controller/composite.(*parentController).sync(0x40001fcc40, {0x4000c41560?, 0x0?})\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:494 +0x2d8\nmetacontroller/pkg/controller/composite.(*parentController).processNextWorkItem(0x40001fcc40)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:296 +0xb8\nmetacontroller/pkg/controller/composite.(*parentController).worker(0x4000895e88?)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:285 +0x2c\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x5d7e?)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:155 +0x44\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x144b638, 0x4000afeff0}, 0x1, 0x400013fe60)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:156 +0x94\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x50?, 0x4000abc000?)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:133 +0x84\nk8s.io/apimachinery/pkg/util/wait.Until(...)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:90\nmetacontroller/pkg/controller/composite.(*parentController).Start.func1.1()\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:261 +0x80\ncreated by metacontroller/pkg/controller/composite.(*parentController).Start.func1\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:259 +0x77c\n","stacktrace":"k8s.io/apimachinery/pkg/util/runtime.HandleCrash\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/runtime/runtime.go:49\nruntime.gopanic\n\t/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838\nruntime.panicmem\n\t/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:220\nruntime.sigpanic\n\t/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/signal_unix.go:818\nk8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetAPIVersion\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/apis/meta/v1/unstructured/unstructured.go:218\nk8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GroupVersionKind\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/apis/meta/v1/unstructured/unstructured.go:426\nmetacontroller/pkg/controller/common/api/v1.RelativeObjectMap.Insert\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/common/api/v1/common.go:36\nmetacontroller/pkg/controller/common/api/v1.RelativeObjectMap.InsertAll\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/common/api/v1/common.go:48\nmetacontroller/pkg/controller/common/api/v1.MakeRelativeObjectMap\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/common/api/v1/common.go:127\nmetacontroller/pkg/controller/composite.(*parentController).syncParentObject\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:533\nmetacontroller/pkg/controller/composite.(*parentController).sync\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:494\nmetacontroller/pkg/controller/composite.(*parentController).processNextWorkItem\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:296\nmetacontroller/pkg/controller/composite.(*parentController).worker\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:285\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:90\nmetacontroller/pkg/controller/composite.(*parentController).Start.func1.1\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:261"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c4e94]
goroutine 643 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x40004fd180?})
 /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/runtime/runtime.go:56 +0xf0
panic({0x1054040, 0x1f1e7b0})
 /opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x20c
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetAPIVersion(...)
 /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/apis/meta/v1/unstructured/unstructured.go:218
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GroupVersionKind(0x0)
 /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/apis/meta/v1/unstructured/unstructured.go:426 +0x44
metacontroller/pkg/controller/common/api/v1.RelativeObjectMap.Insert(0x0?, {0x146a9f8, 0x40005864d8}, 0x0)
 /home/runner/work/metacontroller/metacontroller/pkg/controller/common/api/v1/common.go:36 +0x3c
metacontroller/pkg/controller/common/api/v1.RelativeObjectMap.InsertAll(...)
 /home/runner/work/metacontroller/metacontroller/pkg/controller/common/api/v1/common.go:48
metacontroller/pkg/controller/common/api/v1.MakeRelativeObjectMap({0x146a9f8, 0x40005864d8}, {0x400037ef00, 0x8, 0x4000ac78f8?})
 /home/runner/work/metacontroller/metacontroller/pkg/controller/common/api/v1/common.go:127 +0x54
metacontroller/pkg/controller/composite.(*parentController).syncParentObject(0x40001fcc40, 0x40005864d8)
 /home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:533 +0x268
metacontroller/pkg/controller/composite.(*parentController).sync(0x40001fcc40, {0x4000c41560?, 0x0?})
 /home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:494 +0x2d8
metacontroller/pkg/controller/composite.(*parentController).processNextWorkItem(0x40001fcc40)
 /home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:296 +0xb8
metacontroller/pkg/controller/composite.(*parentController).worker(0x4000895e88?)
 /home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:285 +0x2c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x5d7e?)
 /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:155 +0x44
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x144b638, 0x4000afeff0}, 0x1, 0x400013fe60)
 /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:156 +0x94
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x50?, 0x4000abc000?)
 /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:133 +0x84
k8s.io/apimachinery/pkg/util/wait.Until(...)
 /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:90
metacontroller/pkg/controller/composite.(*parentController).Start.func1.1()
 /home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:261 +0x80
created by metacontroller/pkg/controller/composite.(*parentController).Start.func1
 /home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:259 +0x77c
```

**Comment by nycnewman** [comment]
Found cause but might be interesting to make metacontroller more defensive on returned values.

I have a Python based webhook and it returned:

Desired: {'children': [None,

as the first entry in the desired record. The "None" value causes Metacontroller to throw a panic.

**Comment by grzesuav** [comment]
@nycnewman yes, you must return empty or nil list of children, not list with `nil` elements

**Comment by grzesuav** [comment]
look at https://github.com/metacontroller/metacontroller/blob/v4.3.9/pkg/controller/composite/hooks_test.go#L97, if that is your case it should work. @nycnewman which version of metacontroller are you using ?

**Comment by nycnewman** [comment]
I have tried both 4.3.9 and 4.3.7. The main difference to the test case is that I accidentally returned a string "None" instead of "{}", i.e. something like:

"children": {None}

i.e. invalid JSON.

**Comment by grzesuav** [comment]
ah, got it now, was it clear original post. will try to figure out if it can be better handled on metacontroller level

**Comment by newtondev** [comment]
In metacontroller it seems to handle the code fine. The error raised is for the unmarshalling of the response:

```
sync hook failed: can't unmarshal webhookResponse: json: cannot unmarshal string into Go struct field CompositeHookResponse.children of type []*unstructured.Unstructured
```

**Comment by newtondev** [comment]
I tested with sending payload as:
```
INFO:__main__:/sync sending response {"status": {"working": "fine"}, "children": {None}}
```

On metacontroller:
```
1.7101731637271228e+09	LEVEL(-4)	composite.problemo-controller	Sync	{"object": {"name":"globalsettings"}}
1.7101731637323246e+09	ERROR	failed to sync Problemo 'globalsettings': sync hook failed for Problemo /globalsettings: sync hook failed: can't unmarshal webhookResponse: invalid character 'N' looking for beginning of object key string

metacontroller/pkg/controller/composite.(*parentController).processNextWorkItem
	/home/cnewton/oss/github.com/newtondev/metacontroller/pkg/controller/composite/controller.go:310
metacontroller/pkg/controller/composite.(*parentController).worker
	/home/cnewton/oss/github.com/newtondev/metacontroller/pkg/controller/composite/controller.go:298
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/home/cnewton/go/1.20.11/pkg/mod/k8s.io/apimachinery@v0.25.9/pkg/util/wait/wait.go:157
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/home/cnewton/go/1.20.11/pkg/mod/k8s.io/apimachinery@v0.25.9/pkg/util/wait/wait.go:158
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/cnewton/go/1.20.11/pkg/mod/k8s.io/apimachinery@v0.25.9/pkg/util/wait/wait.go:135
k8s.io/apimachinery/pkg/util/wait.Until
	/home/cnewton/go/1.20.11/pkg/mod/k8s.io/apimachinery@v0.25.9/pkg/util/wait/wait.go:92
metacontroller/pkg/controller/composite.(*parentController).Start.func1.1
	/home/cnewton/oss/github.com/newtondev/metacontroller/pkg/controller/composite/controller.go:27
```

The error message is correctly handled by metacontroller and raised as an error with the unmarshalling of the JSON.

---

I also tested with payload as:
```
INFO:__main__:/sync sending response {"status": {"working": "fine"}, "children": [None]}
```

The error was correctly handled by metacontroller without a panic or a crash:
```
1.710173330438693e+09	LEVEL(-4)	composite.problemo-controller	Sync	{"object": {"name":"globalsettings"}}
1.7101733304408345e+09	ERROR	failed to sync Problemo 'globalsettings': sync hook failed for Problemo /globalsettings: sync hook failed: can't unmarshal webhookResponse: invalid character 'N' looking for beginning of value

metacontroller/pkg/controller/composite.(*parentController).processNextWorkItem
	/home/cnewton/oss/github.com/newtondev/metacontroller/pkg/controller/composite/controller.go:310
metacontroller/pkg/controller/composite.(*parentController).worker
	/home/cnewton/oss/github.com/newtondev/metacontroller/pkg/controller/composite/controller.go:298
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/home/cnewton/go/1.20.11/pkg/mod/k8s.io/apimachinery@v0.25.9/pkg/util/wait/wait.go:157
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/home/cnewton/go/1.20.11/pkg/mod/k8s.io/apimachinery@v0.25.9/pkg/util/wait/wait.go:158
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/cnewton/go/1.20.11/pkg/mod/k8s.io/apimachinery@v0.25.9/pkg/util/wait/wait.go:135
k8s.io/apimachinery/pkg/util/wait.Until
	/home/cnewton/go/1.20.11/pkg/mod/k8s.io/apimachinery@v0.25.9/pkg/util/wait/wait.go:92
metacontroller/pkg/controller/composite.(*parentController).Start.func1.1
	/home/cnewton/oss/github.com/newtondev/metacontroller/pkg/controller/composite/controller.go:274
```

---

There was a panic that was raised in the test instrumentation. I have updated the code for this with some additional test cases.

**Comment by grzesuav** [comment]
thanks @newtondev !


@nycnewman please try one of the latest releases
